security:
    enable_authenticator_manager: true
    providers:
        api_token:
            entity:
                class: App\Entity\User
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        movies:
            custom_authenticators:
                    - App\Security\ApiKeyAuthenticator
            pattern: ^/api
            provider: api_token
            stateless: true

    access_control:
        - { path: ^/api/(movies|movies-has-people|movies-has-type|peoples|type)/, allow_if: "is_fully_authenticated()", methods: [POST, PUT, DELETE] }
        - { path: ^/api/(movies|movies-has-people|movies-has-type|peoples|type)/, allow_if: "is_anonymous() or is_fully_authenticated()", methods: [GET] }

